### PR TITLE
Article Draft: 1000-day-love-affair-with-ember

### PR DESCRIPTION
**Pull request by jwo**
@adamstac Here's my article text for the Love affair with Ember post.

Things of note -- I generate the tweet embeds and default text with a ["tweet_tag" plugin](https://github.com/jwo/jwo.github.com/blob/source/plugins/tweet_tag.rb) ... I'm not sure how you're generating. If this works (jekyll), then GREAT.

If not, I can use #computer-coding to replace the `{% tweet 147056588740505601 %}` with HTML and JS.

### CODE REVIEW

**Comment by adamstac** [comment]
I couldn't find anything for WordPress to easily use the tweet id with a shortcode to make things easier. Seems there's no plugin out there for this.

Could you generate the the HTML and JS?

**Comment by jwo** [comment]
@adamstac ok, the tweet tag replaced with html/js... will be good for SEO as well as no-javascripters.

**Comment by jerodsanto** [comment]
@jwo wow, we really dropped the ball on this article. Embarrassing. So sorry about that. Is this something that you think is still relevant and would like us to publish it? I'm up for it if you are!

**Comment by jwo** [comment]
@jerodsanto No worries; but it probably is a bit out of date at this point. Going to close; will get you something else :)

**Comment by jerodsanto** [comment]
@jwo fair enough. We have resolved to stop neglecting our guest post opportunities in 2016 so rest assured that whatever you come up with _will_ see the light of day (everything I've read of yours is :+1: )

**Comment by jerodsanto** [comment]
@jwo actually, I really enjoyed your #alltimeconferencetalks tweets. I'd love to have that in blog post form. The hard work is over, too. Just do some video embeds and provide a little color on why you love each talk. What do you think about that idea?

**Comment by jwo** [comment]
I think it’s great! jumping all over that one. huzzah!

- jesse

**Pull request closed without merging**
